### PR TITLE
Added posibility to pass a room when using the Dubtrack backend

### PR DESCRIPTION
**Pull request by jonbesga**

### CODE REVIEW

**Comment by txomon** [comment]
Please rebase on master / merge master in so that the tests can be run.

**Comment by jonbesga** [comment]
Done!

**Comment by txomon** [comment]
I have noticed that you have something weird going on with your author/commiter config in git, you may want to have a look on that.

**Comment by jonbesga** [comment]
Thanks for noticing the issue with the author/commit config. It's fixed already!

**Comment by jonbesga** [comment]
This PR is a previous step to #6. As #6 is already merged, I'm closing this one.

**Pull request closed without merging**
